datamodule:
  batch_size: 1
  num_workers: 1
  dataset_type: hover
  targets:
    - sem
    - type
    - inst
  weight_map: False
  normalize_input: False
  rm_overlaps: False
  augmentations:
    - hue_sat
    - non_rigid
    - blur