datamodule:
  batch_size: 1
  num_workers: 1
  weight_map: False
  normalize_input: False
  seg_targets:
    - type
    - sem
  img_transforms:
    - hue_sat
    - blur
    - non_rigid
  inst_transforms:
    - hover
    - dist