[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -v"
testpaths = [
    "src/data/datasets/_tests",
    "src/dl/losses/_tests",
    "src/dl/losses/criterions/_tests",
    "src/dl/optimizers/_tests",
    "src/dl/models/_tests",
    "src/dl/lightning/_tests"
]

markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "required"
]